// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAKUasS5okBHBJEtdQcU0VzGu7rOQWdpE',
    appId: '1:719651971701:web:d66cc4639f321eb75dce3c',
    messagingSenderId: '719651971701',
    projectId: 'xtwitter-app',
    authDomain: 'xtwitter-app.firebaseapp.com',
    storageBucket: 'xtwitter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmZN_NxGbQl9851vgCXTqkSUfQq6BAoVU',
    appId: '1:719651971701:android:d80cf402246090b45dce3c',
    messagingSenderId: '719651971701',
    projectId: 'xtwitter-app',
    storageBucket: 'xtwitter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2s1i8sDKzu-0McEB_0uWijqWyC_kvzd0',
    appId: '1:719651971701:ios:117bfc8fb2a819335dce3c',
    messagingSenderId: '719651971701',
    projectId: 'xtwitter-app',
    storageBucket: 'xtwitter-app.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2s1i8sDKzu-0McEB_0uWijqWyC_kvzd0',
    appId: '1:719651971701:ios:117bfc8fb2a819335dce3c',
    messagingSenderId: '719651971701',
    projectId: 'xtwitter-app',
    storageBucket: 'xtwitter-app.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAKUasS5okBHBJEtdQcU0VzGu7rOQWdpE',
    appId: '1:719651971701:web:0446c6566e6b1b565dce3c',
    messagingSenderId: '719651971701',
    projectId: 'xtwitter-app',
    authDomain: 'xtwitter-app.firebaseapp.com',
    storageBucket: 'xtwitter-app.firebasestorage.app',
  );
}
